### ISSUE TITLE
Merlin

### ISSUE THREAD

**Issue by robsontenorio** [abrakam/Faeria_Cards#9]
Crystal Flower has 4 entries:
- 502 
- 550 
- 551 
- 552 

https://github.com/abrakam/Faeria_Cards/blob/master/CardExport/merlin_shortened.csv

And about CardExport for another languages?

@smoldersan

**Comment by smoldersan** [comment]
Thank you @robsontenorio .

CardExport for other languages should be pushed here by monday.
